version: '3.9'


services:
  snippet-permissions:
    container_name: "snippet-permissions"
    image: ghcr.io/ingsis-group2/snippet-permissions-master:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_KEY}
      NEW_RELIC_APP_NAME: snippet-permissions
    depends_on:
      - snippet-permissions-db

  snippet-permissions-db:
    container_name: "snippet-permissions-db"
    image: postgres:12
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    expose:
      - "5432"
    volumes:
      - snippet-permissions-db:/var/lib/postgresql/data


  snippet-operations:
    container_name: "snippet-operations"
    image: ghcr.io/ingsis-group2/snippet-operations-master:latest
    ports:
      - "8081:8081"
    environment:
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH_SERVER_URI: ${AUTH_SERVER_URI}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_KEY}
      NEW_RELIC_APP_NAME: snippet-operations
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - redis

  asset-service:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8082:8080"
    environment:
      AZURE_HOST: "http://azurite"


  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  snippet-runner:
    container_name: "snippet-runner"
    image: ghcr.io/ingsis-group2/snippet-runner-master:latest
    ports:
      - "8083:8080"
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_KEY}
      NEW_RELIC_APP_NAME: snippet-runner
    volumes:
      - .:/app/data
    depends_on:
      - redis

  printscript-ui:
    container_name: "printscript-ui"
    image: ghcr.io/ingsis-group2/printscript-ui-master:latest
    restart: always
    ports:
      - "5173:5173"

  nginx:
    image: nginx:latest
    restart: always
    env_file:
      - .env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf-master.d/:/etc/nginx/conf.d/default-master.conf:ro
      - ./static:/usr/share/nginx/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx/images/:/usr/share/nginx/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6369"


volumes:
  snippet-permissions-db:
    external: false
  blob:
    external: false
