version: '3.9'


services:
  snippet-permissions:
    container_name: "snippet-permissions"
    image: ghcr.io/ingsis-group2/snippet-permissions-master:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - snippet-permissions-db
    env_file:
      - .env


  snippet-permissions-db:
    container_name: "snippet-permissions-db"
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    expose:
      - "5432"
    volumes:
      - snippet-permissions-db:/var/lib/postgresql/data
    env_file:
      - .env

  snippet-operations:
    container_name: "snippet-operations"
    image: ghcr.io/ingsis-group2/snippet-operations-master:latest
    ports:
      - "8081:8080"
    volumes:
      - ./data:/app/data

  asset-service:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8082:8080"
    environment:
      AZURE_HOST: "http://azurite"


  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  snippet-runner:
    container_name: "snippet-runner"
    image: ghcr.io/ingsis-group2/snippet-runner-master:latest
    ports:
      - "8083:8080"
    volumes:
      - .:/app/data

volumes:
  snippet-permissions-db:
    external: false
  blob:
    external: false
